version: "3.8"
services:
    redis_db:
        image: "redis:alpine"
        expose:
            - 6379
    webserver:
        build: ./node-app
        ports:
            - "3000:3000"
        environment:
            - REDIS_URI=redis://redis_db:6379
        volumes:
            - .:/usr/src/app